# -*- coding: utf-8 -*-
"""20-One Hot Encoding Sklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwXmhvGadvP9aVfOKRxxzHfNx6myNSLW
"""

#O bankayı kullanmaktan vazgeçicek olanların tahminini yapıcaz
#OneHot demek bütün herkesin herşeyin oraya yoğunlaşması demek

import pandas as pd;import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

df=pd.read_csv('churn.csv')
df.head(3)

df=df.drop(columns=["RowNumber","CustomerId","Surname"])

df_dummies=pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True)
df=df_dummies.astype(int)
df.head(3)
#mesela burada az ülke var eğer 100 tane ülke olsaydı sürekli 0,0,0,...1 olduğum ülke gelene kadar 0 girecektim uzun ve kötü gözükecekti

y=df["Exited"]
x=df.drop(columns=["Exited"])

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=33)

rf=RandomForestClassifier(n_estimators=100,random_state=33)
model=rf.fit(x_train,y_train)
model.score(x_test,y_test)

model.predict([[712,31,9,0,5,1,1,200000,0,0,1]])

x.head(2)

from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x=ohe.fit_transform(df[["Geography","Gender"]])
x.toarray()

df.head(3)

xd=ohe.fit_transform([['Geography','Gender']]).toarray()
ohe.get_feature_names_out()

xd=pd.DataFrame(xd)
xd.columns=ohe.get_feature_names_out()
xd

df=df.drop(columns=["Geography","Gender"])
df

df[xd.columns]=xd

df.head(4)

y=df["Exited"]
x=df.drop(columns=["Exited"])

from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()
model=tree.fit(x_train,y_train)
model.score(x_test,y_test)