# -*- coding: utf-8 -*-
"""KNN/En Yakın Komşu Algoritması.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180KMtsu0F15l3Od_K1pcsHueN_e7pMRE
"""

#seleniumla veri çekicez
#sahibindennden her ilden 4 5 tane ilçesinden 2 3 sayfa veri çekicez

!pip install selenium

from selenium import webdriver
import time
import pandas as pd ; import numpy as np
import matplotlib.pyplot as plt

