# -*- coding: utf-8 -*-
"""LabelEncoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWHOGGD2L36WmGxTdTxFwYSfdKKaDRd9
"""

#LabelEncoder nedir
#Kategorisel Veriler numeric verilere çevirilir

#dummy bağımlı değişkenlerde kullanılması zor

import pandas as pd ; import numpy as np
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv("tdf.csv")
df.head(3)

df['Team'].unique()

le=LabelEncoder()
le.fit(df['Team'])

df['Team']=le.transform(df['Team'])

le.classes_

#elimde numeric veri varsa ve bunları kategorisel verilere çevirmek istersem
x=le.inverse_transform(df['Team'])
x

#Hem fit hem transform yapıyor tek seferde hallediyoruz
le2=LabelEncoder()
le2.fit_transform(df['Team'])