# -*- coding: utf-8 -*-
"""Logistic Regresyon (Sınıflandırma)ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_L4hizGeKVQYQUlnfOS9jOS32DuCa4d
"""

import pandas as pd ; import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

#Logistic Regrsesyon
#formulu e^a+bx /1+e^a+bx bu formul 0 ya da 1 verir başka bir sonuç vermez

df=pd.read_csv("card.csv")
df.head(3)

df=df.drop(["ID"],axis=1)
df.head(3)

y=df["default.payment.next.month"]
x=df.drop(["default.payment.next.month"],axis=1)

#kaç tane veri olduğuna bakıyoruz
df.shape

#ezberlemesin overfitting olmasın diye 30k verinin hepsini vermiyorum mesela öğrensin diye parçalayarak veriyorum

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.77, random_state=6)
#random state nedir satırları rastgele veriyorum.Sıralı gelmesin iyice öğrensin diye

log=LogisticRegression()
model=log.fit(x_train,y_train)

model.score(x_test,y_test)

deneme=np.array(x.iloc[1903])
 deneme

#ödeyip ödemediğine bakıyoruz
model.predict([deneme])

y.iloc[1903]

#Bir model 2 'ye Ayrılır
#Model geldi ben bu modeli neyle çözücem sınıflandırma mı Regresyon mu ilk işimiz buna cevap bulmaktır