# -*- coding: utf-8 -*-
"""ML Algoritmaları/LazyPredict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WRJ7zjdF_UeQ-boadQQudWw1MbQxdNm
"""

#LazyPredict bir sürü algoritmayı bünyesinde bulunduran bir framwork gibi bir şey
#Algoritmamda en iyi sonucu veren parametreleri bulmamız için  çok yararlı,overfitting olmasına engel oluyor
!pip install lazypredict

from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer

data=load_breast_cancer()
x=data.data
y=data.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=123)

clf=LazyClassifier(verbose=0,ignore_warnings=True,custom_metric=None)
models,predictions=clf.fit(x_train,x_test,y_train,y_test)

print(models)

from lazypredict.Supervised import LazyRegressor
from sklearn import datasets
from sklearn.utils import shuffle
import numpy as np
import pandas as pd #Import pandas to read the dataset with the suggested method

#boston=datasets.load_boston() #This function is no longer available
# Load the dataset from the original source
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

x,y=shuffle(data,target,random_state=13) #Use the new data and target variables
x=x.astype(np.float32)

reg=LazyRegressor(verbose=0,ignore_warnings=True,custom_metric=None)
models,predictions=reg.fit(x_train,x_test,y_train,y_test)
print(models)