# -*- coding: utf-8 -*-
"""Pandas3DF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GozoFrq0cE-8og0Rjp4tyQxLyihMAoIb
"""

import pandas as pd

#Dataframeleri kullanacağız yani birden fazla sutün kullanacağız
#burada dictionarylerden oluşan bir liste oluşturuyorum
student=[
    {
        'name':'Halil İbrahim',
        'age':23,
        'gender':'Male'
    },
    {

        'name':'Eda',
        'age':24,
        'gender':'Female'


    },
    {
        'name':'Elif',
        'age':22,
        'gender':'Female'
    }
]

print(student)
print(type(student))

#şuan dataframe oluşturuyorum belli olsun diye başına df diye kısaltma ekliyorum

df_student=pd.DataFrame(student)
print()
print(df_student)
print(type(df_student))

print()
print()
#bir dictionary oluşturdum keyler normal keyler ama valuesler bir liste içeriyor ben bundan dataframe oluşturabilirim
teachers={
    'names':['Halil','İbrahim','Elif'],
    'ages':[23,24,22],
    'genders':['Male','Male','Female']
}
print(teachers)
print(type(teachers))
df_teachers=pd.DataFrame(teachers)
print(df_teachers)
print(type(df_teachers))

print()
print()
print()

#burada listeden bir liste oluşturdum
list_of_list=[
    ['ahmet','mehmet','ayşe'],
    [23,24,22],
    ['Male','Male','Female']
]

print(list_of_list)
print(type(list_of_list))
print()
print()
print()

df_list_of_list=pd.DataFrame(list_of_list)
print(df_list_of_list)
print(type(df_list_of_list))
#sutünların üstünde 0 1 2 gibi rkamlar var bunlar ne liste yapısından dolayı pythın kendi otomatik olarak indexleri veriyor

print()
print()
print()

names=['Ahmet','Mahmut','Fatih','Aslı']
print(names)
print(type(names))
print()
print()
print()

df_names=pd.DataFrame(names)
print(df_names)
print(type(df_names))
#bu tek boyutu değil ondan dolayı df oluşturabiliyoruz
print(df_names.ndim)
#kaç boyutlu diye sorduk
print()
print()
print()
"""
players={'name':'hale','age':23}
print(players)
print(type(players))
print()


df_players=pd.DataFrame(players)
#bu şekilde df oluşturamayız klasik dictionaryden df oluşturulamaz
print(df_players)
print(type(df_players))
"""
#dictionaryinin içine series ekledim dataframe oluşturabilmek için
#players dictionaryinin değerleri pandasseries yapıp indexlerini de kendimiz belirledik
players={'Hale':pd.Series(data=[25,'Female','Computer Engineer',165],index=['age','gender','department','height']),
         'Mahmut':pd.Series(data=[26,'Male','Computer Engineer',85],index=['age','gender','department','weight']),
         'Fatih':pd.Series(data=[27,'Male','Computer Engineer'],index=['age','gender','department'])
         }


print(players)
print(type(players))
print()


df_players=pd.DataFrame(players)
print(df_players)
print(type(df_players))