# -*- coding: utf-8 -*-
"""Pandas5VeriAnalizi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPxUUZs2dL6DorPeZyRjNP1CPcaA7HWh
"""

import pandas as pd

review=pd.read_csv('ReviewContent.csv')
print(review)
#bu şekilde az veri okuyabiliyoruz ama biz pandas komutlarıyla bunu daha güzel hale getireceğiz


print(review.info())
#dataframe ile ilgili info veriyor

print(review.head(5))
print()
print(review.tail(5))
print()

print(review.dtypes)
print()

print(review.columns)
#bu yalnızca dataframe de var serieslerde yok satırları gösteriyor bize
#burda columns'un yanına parantez koymadık bu nesneye bağlı bir fonksiyon ondan dolayı
print()

print(review.memory_usage())
print()
#bize kullanılan hafıza miktarını gösteriyor seri geri döndürüyor bize

review=pd.read_csv('ReviewContent.csv')
print(review.head(5))
print()

z=review['Room Price'].sum()
#ismini girdiğim sutünda bulunan tüm değerleri topladık burada
print(z)

print(review['Room Availability'])
#series şeklinde bize sutunu yazdıracak
print()

print(review['Room Availability'].add(10))
#sutunun her satırına 10 ekledim burada
print()
print(review['Room Availability']+10)
#bu da aynı sonucu vericek yani çıkarımımız şu series serisinde bu şekilde de toplama yapabiliyoruz
print()
#4 işlemide bu şekilde yapabiliriz

review=pd.read_csv('ReviewContent.csv')
#city sutunundaki verilere bakalım
print(review['City'])
print()
#value_counts metodu bize şunu döner o sutunda bir değer kaç kere kullanılmış bize onu döner
print(review['City'].value_counts())
print()
print(review['Room Type'])
print()
print(review['Room Type'].value_counts())
print()
print(review['Room Price'].value_counts())
#oda fiyatlarını sıraladım burada
print()
print(review['Room Price'].value_counts().head())
print()
#ilk 5i
#ama ben sıralamak istersem ne kullancağım ?
print(review['Room Price'].sort_values(ascending=False))
#ascending false demesi azalarak değil de artarak sırala diyoruz
print()
print(review['Room Price'].sort_values(ascending=False).head(1))
#burada da büyükten küçüğe sırala ve en büyüğünü göster diyoruz

review=pd.read_csv('ReviewContent.csv')
print(review['City'].sort_values())
#alfabetik sıraya göre sıralıyor
print()
#verimizin tamamını oda fiyatıan göre sıralayalım dersek nasıl yapacağız?
print(review.sort_values('Room Price'))
print()