# -*- coding: utf-8 -*-
"""Preprocessing ve Pandas Dummy Metodu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrScLKOL3lgQ7mJvjYrP_GtuHB7CGT98
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

df=pd.read_csv('audi.csv')
df.head(3)

#çok fazla gereksiz veri sutunu var onları kaldırıyorum
df=df.drop(columns=['index','href','PriceRank','MileageRank','PPYRank','Score'])

df.head(3)

df.info()

#y=ax+b
#mesela ben burada hatchback veya otomatik manuel olmasını katsayı olarak kullanamam.Bunlara kategorisel veri diyoruz
#Benim kesinlikle numeric veriye ihtiyacım var

#Motor hacmi için numeric bir veriye ihtiyacım var
 df.columns=["yıl","kasa","km","motor","ps","vites","yakıt","sahip","fiyat","ppy"]
 df.head(3)

df['motor']

#L'leri attık onlar yerine boşluk koyduk numerice çevireceğiz diye
df["motor"]=df["motor"].str.replace("L","")
df["motor"]

pd.to_numeric(df["motor"])

df.head(3)

#diyoruzki burada df'in içindeki sutunları dummy et sayıya çevir
pd.get_dummies(df,columns=['kasa','vites','yakıt'],drop_first=True)

y=df['fiyat']
x=df.drop(columns=['fiyat'])

lm=LinearRegression()
model=lm.fit(x,y)

#değerleri girip tahmin ettiğimiz kısım burası
model.predict()

#ne oranda tahmin ettiğimizi gösteriyor
model.score(x,y)