# -*- coding: utf-8 -*-
"""Random Forest Regressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gk3gBV0AEYXGqiFQc4SCHFZ08Uhs5rAX
"""

#Eğer elimde 2 tane veri var ve tek grafikte gösteriyorsam regreson çizgisi 1 tane olduğunda tamemen doğru bir sonuç olamaz
#Ama sınıflandırma ile regresyonu birleştirebiliyorum

import pandas as pd ; import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df=pd.read_csv('insurance.csv')
df.head(3)

df=pd.get_dummies(df,columns=['sex','smoker','region'],drop_first=True)
df=df.astype(int)
df.head(3)

y=df['charges']
x=df.drop('charges',axis=1)

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=22)

df.shape

lr=LinearRegression()
model=lr.fit(x_train,y_train)
model.score(x_test,y_test)

#İçinde Kategorisel Veriler var diye en güzel tahmin için RandomForestRegression kullandım
rf=RandomForestRegressor(n_estimators=200)
model=rf.fit(x_train,y_train)
model.score(x_test,y_test)

x.head(4)

#Burada kaç tl sigortamız var onu buldum

model.predict([[22,25,0,1,1,0,1,0]])