# -*- coding: utf-8 -*-
"""Textileçalışmak.pd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxIJA2MIUXzdQRZKn_uAKqbotmyOJtIp
"""

import pandas as pd

review=pd.read_csv('ReviewContent.csv')

print(review)

print(review["Country"])

#UPPER() TÜM HARFLERİ BÜYÜK YAPAR
#LOWER() TÜM HARDLERİ KÜÇÜK YAPAR
#TİTLE() BAŞ HARFLERİ BÜYÜK YAPAR
#LEN()
#python metodları ile karışmasın diye başına str koyarız

print(review["Country"].str.upper())
#tüm harfleri büyük harfe çevirdi
print(review["Country"].str.lower())
#tüm harfleri küçük harfe çevirdi
print(review["Country"].str.title())
#tüm baş harfleri büyük harfe çevir

#buradaki tüm değişiklikler geçici eğer kalıcı yapmak istiyorsak
review["Country"]=review["Country"].str.upper()
#bu formatla birlikta artık tüm harfler büyük oldu değişkene atadık çünkü

print(len("benim adım halil"))

print(len(review["Country"]))
#country sutununun uzunluğunu (satır sayısını) bize veriyor
#ama bize sutundaki verilerin uzunluğu lazım bunun içinde
print(review['Country'].str.len())
#o sutunun satırlarının veri uzunluğunu bu şekilde bize veriyor

print("halil ibrahim kurnaz".replace("i","ı"))
#harfleri istediğimiz harflerle değştirebeliyoruz bu methodla beraber

print(review["Room Type"].str.replace('room','Room'))

print(review["City"])
#filtreleme yapıcaz şimdi
#içinde York ifadesini geçtiği verileri bana döndür diyoruz burada
#öncelikle var olan sutunun satılarının hepsini büyük harfe çeviriyorum
print(review["City"].str.upper().str.contains("YORK"))
#içinde York ifadesini geçtiği verileri bana döndür diyoruz burada

mask=review["City"].str.upper().str.contains("YORK")
#bunuun true döndüğü her satırı döndürüyoruz bu şekilde
print(review[mask])

#... ile başlayan bir veriyi ggörmek istiyorsak eğer
mask=review["City"].str.upper().str.startswith("LOS")
print(review[mask])
#... ile biten arıyorsakda startswitch yerine endswith ifadesini kullancağız

print(review["City"].str.strip())
#satırın başında ya da sonunda boşluklar arsa onları siliyor
#lstrip olursa soldaki başlangıçtaki boşluğu yok edicek
#rstrip olursa sağdaki sonraki boşluğu yok edicek

print("   ben çok yakışıklıyım    ".strip())

#split metodu içine verrdiğimiz parametreye göre ayırıyor ve liste şeklinde döndürüyor
#liste şeklinde değilde bir df şeklinde dönmesi içinde bir parametre daha yazarız spliy(  , expand=True)

print(" benim adım halil ibrahim kurnaz".split(' '))

print(review["City"].str.split(' ').str.get(0))