# -*- coding: utf-8 -*-
"""Train Test Split Metodu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTH3jjiPur9cYsxjkfRLDDwxopjn9umW
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_csv('audi.csv')
df.head()

df=df[["Year","Type","Mileage(miles)","Engine","PS","Transmission","Fuel","Number_of_Owners","Price(£)"]]
df.head(3)

df.columns=["yil","kasa","mil","motor","ps","vites","yakit","sahip","fiyat"]
df.head(3)

df['motor']=df['motor'].str.replace('L','')
df['motor']=pd.to_numeric(df['motor'])
df.head(3)

#burada kategorisel verileri 1 veya 0 a çevirerek numeric yaptm sonra bunları da df'e atadım
df_dummies=pd.get_dummies(df,columns=["kasa","vites","yakit"],drop_first=True)
df_dummies=df_dummies.astype(int)
df=df_dummies

y=df["fiyat"]
x=df.drop("fiyat",axis=1)

#train test model oluşturulmadan önce yapılıyor
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70,random_state=33)

lm=LinearRegression()
model=lm.fit(x_train,y_train)
model.score(x_test,y_test)

#bir yandan öğretmek istiyorum bir yandan da doğru öğretmek istiyorum
#Modelin güvenilirliği

df.head(3)

